<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Dell-Latitude" failures="1" tests="8" name="TestSauceLabs" time="58.754" errors="0" timestamp="2024-08-23T22:58:01 IST">
  <testcase classname="testSauceDemo.locked_out_user" name="login_locked_User" time="7.37"/>
  <testcase classname="testSauceDemo.TestValidCompleteFlow" name="validloginpage" time="6.436"/>
  <testcase classname="testSauceDemo.performance_glitch_user" name="login_glitch_User" time="12.041"/>
  <testcase classname="testSauceDemo.login_ProblemUser" name="login_Problem_User" time="6.994"/>
  <testcase classname="testSauceDemo.TestValidCompleteFlow" name="addProductToCart" time="8.773"/>
  <testcase classname="testSauceDemo.TestValidCompleteFlow" name="enterUserInfo" time="6.614"/>
  <testcase classname="testSauceDemo.TestValidCompleteFlow" name="Checkout" time="1.292"/>
  <testcase classname="testSauceDemo.TestValidCompleteFlow" name="completeCheckout" time="0.041">
    <failure type="java.lang.AssertionError" message="expected [Checkout: Complete!] but found [CHECKOUT: COMPLETE!]">
      <![CDATA[java.lang.AssertionError: expected [Checkout: Complete!] but found [CHECKOUT: COMPLETE!]
at pagefiles_SauceDemo.CompleteCheckout.ValidateCheckout(CompleteCheckout.java:34)
at testSauceDemo.TestValidCompleteFlow.completeCheckout(TestValidCompleteFlow.java:103)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1623)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- completeCheckout -->
</testsuite> <!-- TestSauceLabs -->
